---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files

      - id: mixed-line-ending
        alias: check-line-endings
        name: check-line-endings
        args: ['--fix=no']

      - id: check-xml
        name: check for malformed *.mm files
        types: ["file"]
        files: '.*\.mm$'

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.1
    hooks:
      - id: yamllint

  - repo: https://github.com/jmknoble/json-indent
    rev: v2.6.2
    hooks:
      - id: json-indent
        args: ['--newlines=linux']

  - repo: https://github.com/jmknoble/markdown-toc
    rev: v0.3.0
    hooks:
      - id: markdown-toc
        args: ['--heading-level', '2', '--skip-level', '1']

...
